---
title: "adam paul lab-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup Steps

First, I need to load the tidyverse.

library(tidyverse)

Reading the data file we'll be working with.

plastic_waste <- read.csv("data/plastic-waste.csv")


#Exercises!

The first thing the exercise has us do is look at the data broadly.

What the code below is doing, for my own sake, is using ggplot to create a graph. 
  Data = plastic_waste picks out the dataset
  aes is aesthetics, which is the basic layout of the graph, such as...
  x= what is on the x-axis
  + indicates the next step in the process
  geom_histogram is picking out a histogram. geom indicates the family of graphical procedures.
    Remember the documentation will have these different commands, as will a google search.
  Binwidth picks how much data is contained within each bar.

ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.2)

Looking at the graph, there's an outlier way away from all the others. One way we're shown to find out what country
  is to filter for only results that are above a cutoff point

plastic_waste %>%
  filter(plastic_waste_per_cap > 3.5)

This reveals that it is Trinidad and Tobago.



#Question 1

1.1. Plot, using histograms, the distribution of plastic waste per capita faceted by continent. What can you say  about how the continents compare to each other in terms of their plastic waste per capita?

ggplot(data = plastic_waste, aes(x=plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.2) +
  facet_grid( ~ continent)

What I notice is that North America, South America, and Asia are the only three that break .5 per capita.
  Of these three, the one with the most, by a good margin, is NA. 
  The continent with the average appearing to be the lowest is Africa, though that may be a consequence of lowest usage.
  Uniquely, though there are some high producers in Asia, it comes the next closest (on average) to lowest waste per capita.



#Question 2

For the next part, we're looking the same information using a density plot. Several iterations are done, resulting in the one below.

ggplot(data = plastic_waste, 
       mapping = aes(x = plastic_waste_per_cap, 
                     color = continent, 
                     fill = continent)) +
  geom_density(alpha = 0.7)

However, we can improve upon this too.

2.1. Recreate the density plots above using a different (lower) alpha level that works better for displaying the density curves for all continents.

ggplot(data = plastic_waste, 
       mapping = aes(x = plastic_waste_per_cap, 
                     color = continent, 
                     fill = continent)) +
  geom_density(alpha = 0.2)

After exploring some, I found 0.2 to be a good number that reveals the full set.

2.2. Describe why we defined the color and fill of the curves by mapping aesthetics of the plot but we defined the alpha level as a characteristic of the plotting geom.

We used aes for the color and fill of the curves because if we didn't we wouldn't get the legend with information about what the colors mean. defining alpha level as a characteristic is fine because we don't need to include it in the legend, as it is being done for visualization purposes. However, not knowing what each colour means would make the graph basically useless.

#Question 3

Another way to visualize the data is with side-by-side box plots.

ggplot(data = plastic_waste, 
       mapping = aes(x = continent, 
                     y = plastic_waste_per_cap)) +
  geom_boxplot()


3.1. Convert your side-by-side box plots from the previous task to violin plots. What do the violin plots reveal that box plots do not? What features are apparent in the box plots but not in the violin plots?


ggplot(data = plastic_waste, 
       mapping = aes(x = continent, 
                     y = plastic_waste_per_cap)) +
  geom_violin()
  
The violin plot reveals that there is a massive amount of skew in North America.
The boxplot lets us know the specific outlier locations, as well as accurately marking the interquartile ranges.

#Question 4

4.1. Visualize the relationship between plastic waste per capita and mismanaged plastic waste per capita using a scatterplot. Describe the relationship.

ggplot(data = plastic_waste,
  mapping = aes(x= mismanaged_plastic_waste_per_cap,
                y = plastic_waste_per_cap)) +
  geom_point()
  
There is an extremely subtle relationship between mismanaged plastic waste per capita and plastic waste per capita,
  but it is hard to notice.
  
4.2. color the points in the scatterplot by continent. Does there seem to be any clear distinctions between continents with respect to how plastic waste per capita and mismanaged plastic waste per capita are associated?

ggplot(data = plastic_waste,
  mapping = aes(x= mismanaged_plastic_waste_per_cap,
                y = plastic_waste_per_cap,
                color = continent)) +
  geom_point() +
  scale_color_viridis_d()
  
North America seems to have the most inconsistent relationship between the two variables, whereas Africa and Asia
  have very linear relationships. Europe has a very sharp relationship between waste and mismanaged waste, where it goes up considerably in waste but not as quickly in mismanaged waste.
  
4.3. Visualize the relationship between plastic waste per capita and total population as well as plastic waste per capita and coastal population. You will need to make two separate plots. Do either of these pairs of variables appear to be more strongly linearly associated?

Total population

ggplot(data = plastic_waste,
  mapping = aes(x= total_pop,
                y = plastic_waste_per_cap)) +
  geom_point()

Coastal population

ggplot(data = plastic_waste,
  mapping = aes(x= coastal_pop,
                y = plastic_waste_per_cap)) +
  geom_point()
  
Coastal pop seems to have a more strongly correlated relationship with plastic waste, such that the less
coastal a population is, the less waste they produce.